### 1. 创建订单
POST http://localhost:8081/api/v1/orders
Content-Type: application/json

{
  "orderNo": "TEST001",
  "amount": 99.90
}

### 2. 查询订单（把下面的 orderId 换成上一步返回的 orderId）
GET http://localhost:8081/api/v1/orders/a24081fba74041149a274823a7821e84

### 3. 更新订单状态（支付服务调用，也可手动测试）
PUT http://localhost:8081/api/v1/orders/a24081fba74041149a274823a7821e84/status
Content-Type: application/json

{
  "status": "PAID",
  "payId": "test_pay_123"
}