### 1. 创建订单
POST http://localhost:8081/api/v1/orders
Content-Type: application/json

{
  "orderNo": "TEST001",
  "amount": 99.90
}

### 2. 查询订单（把下面的 orderId 换成上一步返回的 orderId）
GET http://localhost:8081/api/v1/orders/e26f981aab8e444aa1decdb619a6b93a

### 3. 发起支付
POST http://localhost:8081/api/v1/orders/e26f981aab8e444aa1decdb619a6b93a/pay
Content-Type: application/json

{
  "payMethod": "BALANCE",
  "amount": 99.90
}